name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-test-auth:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:16.8
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: obald123
          POSTGRES_DB: student_registration
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: stu_2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: stu_2/student-registration-backend
      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: stu_2/student-registration-backend
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        working-directory: stu_2/student-registration-backend
      - name: Run auth tests
        run: npx mocha --timeout 10000 -r ts-node/register src/test/auth.test.ts
        working-directory: stu_2/student-registration-backend

  backend-test-controllers:
    runs-on: ubuntu-latest
    needs: backend-test-auth
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: stu_2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: stu_2/student-registration-backend
      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: stu_2/student-registration-backend
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        working-directory: stu_2/student-registration-backend
      - name: Run controllers tests
        run: npx mocha --timeout 10000 -r ts-node/register src/test/controllers.test.ts
        working-directory: stu_2/student-registration-backend

  backend-test-other:
    runs-on: ubuntu-latest
    needs: backend-test-auth
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: testdb
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    env:
      DATABASE_URL: ${{ secrets.DATABASE_URL }}
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
    steps:
      - uses: actions/checkout@v4
        with:
          path: stu_2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: stu_2/student-registration-backend
      - name: Generate Prisma client
        run: npx prisma generate
        working-directory: stu_2/student-registration-backend
      - name: Run Prisma migrations
        run: npx prisma migrate deploy
        working-directory: stu_2/student-registration-backend
      - name: Run other tests
        run: npx mocha --timeout 10000 -r ts-node/register src/test/edgecases.test.ts src/test/extra.test.ts src/test/fullcover.test.ts src/test/registrationNumber.test.ts src/test/serverError.test.ts src/test/swagger.test.ts
        working-directory: stu_2/student-registration-backend

  frontend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          path: stu_2
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install dependencies
        run: npm install
        working-directory: stu_2/student-registration-frontend
      - name: Build frontend
        run: npm run build
        working-directory: stu_2/student-registration-frontend

      - name: Run frontend tests
        run: npm test
        working-directory: stu_2/student-registration-frontend
